### ISSUE TITLE
ipa-healthcheck suddenly looking up Server-Cert instead of fqdn for externally provided https and ldaps certificates

### ISSUE THREAD

**Issue by arnoxit** [freeipa/freeipa-healthcheck#373]
We are suddenly getting the following healthcheck failures after updating 389-ds packages to 2.7.0-10.el9_7 from 2.7.0.el9_7:

```
EXPERIMENTAL 1 06:35:05 root@idm-dub-3.internal.transficc.net:~# ipa-healthcheck --failures-only
/usr/lib/python3.9/site-packages/pki/server/healthcheck/meta/connectivity.py:131: The PKIConnection parameter in SystemCertClient.__init__() has been deprecated. Provide SubsystemClient instead.
Unable to find server cert nickname in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/dse.ldif
Unable to find server cert nickname in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/dse.ldif
Unable to find server cert nickname in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/dse.ldif
Unable to find server cert nickname in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/dse.ldif
Unable to find server cert nickname in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/dse.ldif
[
  {
    "source": "ipahealthcheck.ipa.certs",
    "check": "IPAUserProvidedExpirationCheck",
    "result": "CRITICAL",
    "uuid": "722b814a-59b4-4f0a-813c-923eafa66604",
    "when": "20260304063537Z",
    "duration": "0.109632",
    "kw": {
      "exception": "'NoneType' object has no attribute 'issuer'",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/core/core.py\", line 56, in run_plugin\n    for result in plugin.check():\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/core/plugin.py\", line 18, in wrapper\n    for result in f(*args, **kwds):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/ipa/certs.py\", line 530, in check\n    if is_ipa_issued_cert(api, cert):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/ipa/certs.py\", line 46, in is_ipa_issued_cert\n    return certs.is_ipa_issued_cert(myapi, cert)\n  File \"/usr/lib/python3.9/site-packages/ipaserver/install/certs.py\", line 143, in is_ipa_issued_cert\n    return DN(cert.issuer) == cacert_subject\nAttributeError: 'NoneType' object has no attribute 'issuer'\n"
    }
  },
  {
    "source": "ipahealthcheck.ipa.certs",
    "check": "IPACertTracking",
    "result": "CRITICAL",
    "uuid": "ca430c09-535b-4eec-9c72-5a1744b000b0",
    "when": "20260304063538Z",
    "duration": "0.768189",
    "kw": {
      "exception": "Could not find the cert Server-Cert in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/core/core.py\", line 56, in run_plugin\n    for result in plugin.check():\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/core/plugin.py\", line 18, in wrapper\n    for result in f(*args, **kwds):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/ipa/certs.py\", line 558, in check\n    requests = get_expected_requests(self.ca, self.ds, self.serverid,\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/ipa/certs.py\", line 140, in get_expected_requests\n    if not connected or ds_db.is_ipa_issued_cert(api, ds_nickname):\n  File \"/usr/lib/python3.9/site-packages/ipaserver/install/certs.py\", line 711, in is_ipa_issued_cert\n    raise RuntimeError(\"Could not find the cert %s in %s\"\nRuntimeError: Could not find the cert Server-Cert in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/\n"
    }
  },
  {
    "source": "ipahealthcheck.ipa.certs",
    "check": "IPACertDNSSAN",
    "result": "CRITICAL",
    "uuid": "3d9e347b-da19-4427-9175-b1fe8685cd64",
    "when": "20260304063539Z",
    "duration": "0.780821",
    "kw": {
      "exception": "Could not find the cert Server-Cert in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/core/core.py\", line 56, in run_plugin\n    for result in plugin.check():\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/core/plugin.py\", line 18, in wrapper\n    for result in f(*args, **kwds):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/ipa/certs.py\", line 628, in check\n    requests = get_expected_requests(self.ca, self.ds, self.serverid,\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/ipa/certs.py\", line 140, in get_expected_requests\n    if not connected or ds_db.is_ipa_issued_cert(api, ds_nickname):\n  File \"/usr/lib/python3.9/site-packages/ipaserver/install/certs.py\", line 711, in is_ipa_issued_cert\n    raise RuntimeError(\"Could not find the cert %s in %s\"\nRuntimeError: Could not find the cert Server-Cert in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/\n"
    }
  },
  {
    "source": "ipahealthcheck.ipa.certs",
    "check": "IPANSSChainValidation",
    "result": "ERROR",
    "uuid": "d3b7b2ce-2b82-4900-82d6-fd1abec30380",
    "when": "20260304063541Z",
    "duration": "0.203300",
    "kw": {
      "key": "/etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET:Server-Cert",
      "dbdir": "/etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/",
      "nickname": "Server-Cert",
      "reason": ": certutil: could not find certificate named \"Server-Cert\": PR_FILE_NOT_FOUND_ERROR: File not found\n",
      "msg": "Validation of {nickname} in {dbdir} failed: {reason}"
    }
  },
  {
    "source": "ipahealthcheck.ipa.certs",
    "check": "IPACertRevocation",
    "result": "CRITICAL",
    "uuid": "303f9667-1f34-4478-bb0d-8050c7d86aff",
    "when": "20260304063543Z",
    "duration": "0.783668",
    "kw": {
      "exception": "Could not find the cert Server-Cert in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/core/core.py\", line 56, in run_plugin\n    for result in plugin.check():\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/core/plugin.py\", line 18, in wrapper\n    for result in f(*args, **kwds):\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/ipa/certs.py\", line 1359, in check\n    requests = get_expected_requests(self.ca, self.ds, self.serverid,\n  File \"/usr/lib/python3.9/site-packages/ipahealthcheck/ipa/certs.py\", line 140, in get_expected_requests\n    if not connected or ds_db.is_ipa_issued_cert(api, ds_nickname):\n  File \"/usr/lib/python3.9/site-packages/ipaserver/install/certs.py\", line 711, in is_ipa_issued_cert\n    raise RuntimeError(\"Could not find the cert %s in %s\"\nRuntimeError: Could not find the cert Server-Cert in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/\n"
    }
  }
]

```

Certificates are from Letsencrypt and are valid and healthchecks were clean on this server before the update of this package and are still valid on other ipa servers in the topology.

Comparing verbose debug healthcheck information from before (from a snapshot) and after the update with the same certificate I can see the following:

before:
```
Calling check <ipahealthcheck.ipa.certs.IPAUserProvidedExpirationCheck object at 0x7f74196858b0>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Issued by IPA, skipping
  Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Starting external process
  args=['/usr/bin/certutil', '-d', 'sql:/etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/', '-L', '-n', 'idm-dub-3.internal.transficc.net', '-a', '-f', '/etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/pwdfile.txt']                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  Process finished, return code=0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  stdout=-----BEGIN CERTIFICATE-----                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  MIIGTjCCBTagAwIBAgISBZMgvlMf9i3I4ReJNWD3L8L2MA0GCSqGSIb3DQEBCwUA^M                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
```
after:
```
  Calling check <ipahealthcheck.ipa.certs.IPAUserProvidedExpirationCheck object at 0x7fc90d265520>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Issued by IPA, skipping
  Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
  Unable to find server cert nickname in /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/dse.ldif                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  Falling back to nickname Server-Cert                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  Starting external process
  args=['/usr/bin/certutil', '-d', 'sql:/etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/', '-L', '-n', 'Server-Cert', '-a', '-f', '/etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/pwdfile.txt']                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  Process finished, return code=255                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  stdout=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  stderr=certutil: Could not find cert: Server-Cert                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  : PR_FILE_NOT_FOUND_ERROR: File not found                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
```

As far as I can see the nsSSLPersonalitySSL value has not changed in the dse.ldif and is still the fqdn so I am not sure why it is falling back to looking for the default 'Server-Cert' as the certificate alias. The correct fqdn cert is in the /etc/dirsrv/slapd-INTERNAL-TRANSFICC-NET/ database.

**Comment by arnoxit** [comment]
Aha... found it... the update has changed the case of the dns:

before:
```
  dn: cn=RSA,cn=encryption,cn=config                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  cn: RSA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  modifiersName: cn=directory manager                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  modifyTimestamp: 20240629132410Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  nsSSLActivation: on                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  nsSSLPersonalitySSL: idm-dub-3.internal.transficc.net                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  nsSSLToken: internal (software)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
- objectClass: top                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
| objectClass: nsEncryptionModule                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
```
after:
```
  dn: cn=rsa,cn=encryption,cn=config                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  cn: RSA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  modifiersName: cn=directory manager                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  modifyTimestamp: 20240629132410Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  nsSSLActivation: on                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  nsSSLPersonalitySSL: idm-dub-3.internal.transficc.net                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  nsSSLToken: internal (software)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
- objectClass: top                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
| objectClass: nsEncryptionModule                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
```
